/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QLabel *label_rec_rar;
    QLabel *label_rec_lar;
    QLabel *label_rec_rec;
    QLabel *label_rec_volt;
    QLabel *label_rec_ampere;
    QLabel *label_rec_estop;
    QLabel *label_rec_bump;
    QLabel *label_rec_cliff;
    QLabel *label_rec_ir;
    QLabel *label_tran_rdr;
    QLabel *label_rec_chk;
    QLabel *label_receive_data;
    QLabel *label_rec_yaw_vel;
    QLabel *label_rec_yaw_heading;
    QLabel *label_rec_lec;
    QLabel *label_rec_gpio1;
    QLabel *label_rec_gpio2;
    QLabel *label_rec_gpio3;
    QLabel *label_rec_gpio4;
    QLabel *label_rec_gpio5;
    QLabel *label_rec_gpio6;
    QLabel *label_rec_gpio7;
    QLabel *label_rec_gpio8;
    QLabel *label_transmit_data;
    QLabel *label_tran_ldr;
    QLabel *label_tran_led1;
    QLabel *label_tran_led6;
    QLabel *label_tran_led8;
    QLabel *label_tran_estop;
    QLabel *label_tran_led4;
    QLabel *label_tran_led7;
    QLabel *label_tran_led2;
    QLabel *label_tran_led3;
    QLabel *label_tran_led5;
    QLabel *label_tran_chk;
    QLabel *label_receive_hz;
    QLabel *label_receive_hz_value;
    QPushButton *connect_btn;
    QLabel *label_rec_rec_value;
    QLabel *label_rec_lec_value;
    QLabel *label_rec_rar_value;
    QLabel *label_rec_lar_value;
    QLabel *label_rec_ampere_value;
    QLabel *label_rec_volt_value;
    QLabel *label_rec_gpio6_value;
    QLabel *label_rec_gpio1_value;
    QLabel *label_rec_gpio8_value;
    QLabel *label_rec_estop_value;
    QLabel *label_rec_gpio4_value;
    QLabel *label_rec_gpio7_value;
    QLabel *label_rec_gpio2_value;
    QLabel *label_rec_gpio5_value;
    QLabel *label_rec_gpio3_value;
    QLabel *label_rec_cliff_value;
    QLabel *label_rec_bump_value;
    QLabel *label_rec_ir_value;
    QLabel *label_rec_chk_value;
    QLabel *label_rec_yaw_heading_value;
    QLabel *label_rec_yaw_vel_value;
    QLabel *label_tran_chk_value;
    QTextEdit *textEdit;
    QComboBox *comboBox_transmit_estop;
    QComboBox *comboBox_transmit_gpio1;
    QComboBox *comboBox_transmit_gpio2;
    QComboBox *comboBox_transmit_gpio3;
    QComboBox *comboBox_transmit_gpio4;
    QComboBox *comboBox_transmit_gpio5;
    QComboBox *comboBox_transmit_gpio6;
    QComboBox *comboBox_transmit_gpio7;
    QComboBox *comboBox_transmit_gpio8;
    QComboBox *comboBox_transmit_rdr;
    QComboBox *comboBox_transmit_ldr;
    QLabel *label_debug;
    QLabel *label_checksum;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1562, 1068);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        label_rec_rar = new QLabel(centralwidget);
        label_rec_rar->setObjectName(QString::fromUtf8("label_rec_rar"));
        label_rec_rar->setGeometry(QRect(1140, 130, 221, 34));
        label_rec_lar = new QLabel(centralwidget);
        label_rec_lar->setObjectName(QString::fromUtf8("label_rec_lar"));
        label_rec_lar->setGeometry(QRect(900, 130, 211, 34));
        label_rec_rec = new QLabel(centralwidget);
        label_rec_rec->setObjectName(QString::fromUtf8("label_rec_rec"));
        label_rec_rec->setGeometry(QRect(590, 130, 281, 34));
        label_rec_volt = new QLabel(centralwidget);
        label_rec_volt->setObjectName(QString::fromUtf8("label_rec_volt"));
        label_rec_volt->setGeometry(QRect(188, 130, 91, 34));
        label_rec_ampere = new QLabel(centralwidget);
        label_rec_ampere->setObjectName(QString::fromUtf8("label_rec_ampere"));
        label_rec_ampere->setGeometry(QRect(30, 130, 129, 34));
        label_rec_estop = new QLabel(centralwidget);
        label_rec_estop->setObjectName(QString::fromUtf8("label_rec_estop"));
        label_rec_estop->setGeometry(QRect(990, 240, 81, 34));
        label_rec_bump = new QLabel(centralwidget);
        label_rec_bump->setObjectName(QString::fromUtf8("label_rec_bump"));
        label_rec_bump->setGeometry(QRect(305, 350, 129, 34));
        label_rec_cliff = new QLabel(centralwidget);
        label_rec_cliff->setObjectName(QString::fromUtf8("label_rec_cliff"));
        label_rec_cliff->setGeometry(QRect(164, 350, 129, 34));
        label_rec_ir = new QLabel(centralwidget);
        label_rec_ir->setObjectName(QString::fromUtf8("label_rec_ir"));
        label_rec_ir->setGeometry(QRect(51, 350, 61, 34));
        label_tran_rdr = new QLabel(centralwidget);
        label_tran_rdr->setObjectName(QString::fromUtf8("label_tran_rdr"));
        label_tran_rdr->setGeometry(QRect(1054, 700, 231, 34));
        label_rec_chk = new QLabel(centralwidget);
        label_rec_chk->setObjectName(QString::fromUtf8("label_rec_chk"));
        label_rec_chk->setGeometry(QRect(32, 458, 129, 30));
        label_receive_data = new QLabel(centralwidget);
        label_receive_data->setObjectName(QString::fromUtf8("label_receive_data"));
        label_receive_data->setGeometry(QRect(30, 70, 291, 34));
        QFont font;
        font.setPointSize(13);
        font.setBold(true);
        font.setWeight(75);
        label_receive_data->setFont(font);
        label_rec_yaw_vel = new QLabel(centralwidget);
        label_rec_yaw_vel->setObjectName(QString::fromUtf8("label_rec_yaw_vel"));
        label_rec_yaw_vel->setGeometry(QRect(406, 456, 171, 34));
        label_rec_yaw_heading = new QLabel(centralwidget);
        label_rec_yaw_heading->setObjectName(QString::fromUtf8("label_rec_yaw_heading"));
        label_rec_yaw_heading->setGeometry(QRect(200, 456, 191, 34));
        label_rec_lec = new QLabel(centralwidget);
        label_rec_lec->setObjectName(QString::fromUtf8("label_rec_lec"));
        label_rec_lec->setGeometry(QRect(300, 129, 281, 34));
        label_rec_gpio1 = new QLabel(centralwidget);
        label_rec_gpio1->setObjectName(QString::fromUtf8("label_rec_gpio1"));
        label_rec_gpio1->setGeometry(QRect(880, 241, 81, 34));
        label_rec_gpio2 = new QLabel(centralwidget);
        label_rec_gpio2->setObjectName(QString::fromUtf8("label_rec_gpio2"));
        label_rec_gpio2->setGeometry(QRect(758, 242, 81, 34));
        label_rec_gpio3 = new QLabel(centralwidget);
        label_rec_gpio3->setObjectName(QString::fromUtf8("label_rec_gpio3"));
        label_rec_gpio3->setGeometry(QRect(635, 242, 81, 34));
        label_rec_gpio4 = new QLabel(centralwidget);
        label_rec_gpio4->setObjectName(QString::fromUtf8("label_rec_gpio4"));
        label_rec_gpio4->setGeometry(QRect(520, 242, 81, 34));
        label_rec_gpio5 = new QLabel(centralwidget);
        label_rec_gpio5->setObjectName(QString::fromUtf8("label_rec_gpio5"));
        label_rec_gpio5->setGeometry(QRect(390, 242, 81, 34));
        label_rec_gpio6 = new QLabel(centralwidget);
        label_rec_gpio6->setObjectName(QString::fromUtf8("label_rec_gpio6"));
        label_rec_gpio6->setGeometry(QRect(270, 242, 81, 34));
        label_rec_gpio7 = new QLabel(centralwidget);
        label_rec_gpio7->setObjectName(QString::fromUtf8("label_rec_gpio7"));
        label_rec_gpio7->setGeometry(QRect(150, 242, 81, 34));
        label_rec_gpio8 = new QLabel(centralwidget);
        label_rec_gpio8->setObjectName(QString::fromUtf8("label_rec_gpio8"));
        label_rec_gpio8->setGeometry(QRect(30, 242, 81, 34));
        label_transmit_data = new QLabel(centralwidget);
        label_transmit_data->setObjectName(QString::fromUtf8("label_transmit_data"));
        label_transmit_data->setGeometry(QRect(1180, 630, 331, 34));
        QFont font1;
        font1.setPointSize(14);
        font1.setBold(true);
        font1.setWeight(75);
        label_transmit_data->setFont(font1);
        label_tran_ldr = new QLabel(centralwidget);
        label_tran_ldr->setObjectName(QString::fromUtf8("label_tran_ldr"));
        label_tran_ldr->setGeometry(QRect(1320, 702, 231, 34));
        label_tran_led1 = new QLabel(centralwidget);
        label_tran_led1->setObjectName(QString::fromUtf8("label_tran_led1"));
        label_tran_led1->setGeometry(QRect(314, 809, 81, 34));
        label_tran_led6 = new QLabel(centralwidget);
        label_tran_led6->setObjectName(QString::fromUtf8("label_tran_led6"));
        label_tran_led6->setGeometry(QRect(1004, 810, 81, 34));
        label_tran_led8 = new QLabel(centralwidget);
        label_tran_led8->setObjectName(QString::fromUtf8("label_tran_led8"));
        label_tran_led8->setGeometry(QRect(1279, 810, 81, 34));
        label_tran_estop = new QLabel(centralwidget);
        label_tran_estop->setObjectName(QString::fromUtf8("label_tran_estop"));
        label_tran_estop->setGeometry(QRect(164, 808, 81, 34));
        label_tran_led4 = new QLabel(centralwidget);
        label_tran_led4->setObjectName(QString::fromUtf8("label_tran_led4"));
        label_tran_led4->setGeometry(QRect(730, 810, 81, 34));
        label_tran_led7 = new QLabel(centralwidget);
        label_tran_led7->setObjectName(QString::fromUtf8("label_tran_led7"));
        label_tran_led7->setGeometry(QRect(1143, 810, 81, 34));
        label_tran_led2 = new QLabel(centralwidget);
        label_tran_led2->setObjectName(QString::fromUtf8("label_tran_led2"));
        label_tran_led2->setGeometry(QRect(453, 810, 81, 34));
        label_tran_led3 = new QLabel(centralwidget);
        label_tran_led3->setObjectName(QString::fromUtf8("label_tran_led3"));
        label_tran_led3->setGeometry(QRect(590, 810, 81, 34));
        label_tran_led5 = new QLabel(centralwidget);
        label_tran_led5->setObjectName(QString::fromUtf8("label_tran_led5"));
        label_tran_led5->setGeometry(QRect(865, 810, 81, 34));
        label_tran_chk = new QLabel(centralwidget);
        label_tran_chk->setObjectName(QString::fromUtf8("label_tran_chk"));
        label_tran_chk->setGeometry(QRect(1395, 811, 129, 34));
        label_receive_hz = new QLabel(centralwidget);
        label_receive_hz->setObjectName(QString::fromUtf8("label_receive_hz"));
        label_receive_hz->setGeometry(QRect(380, 67, 61, 40));
        QFont font2;
        font2.setPointSize(12);
        font2.setBold(true);
        font2.setWeight(75);
        label_receive_hz->setFont(font2);
        label_receive_hz_value = new QLabel(centralwidget);
        label_receive_hz_value->setObjectName(QString::fromUtf8("label_receive_hz_value"));
        label_receive_hz_value->setGeometry(QRect(470, 68, 191, 40));
        label_receive_hz_value->setFont(font2);
        connect_btn = new QPushButton(centralwidget);
        connect_btn->setObjectName(QString::fromUtf8("connect_btn"));
        connect_btn->setGeometry(QRect(1270, 30, 261, 48));
        label_rec_rec_value = new QLabel(centralwidget);
        label_rec_rec_value->setObjectName(QString::fromUtf8("label_rec_rec_value"));
        label_rec_rec_value->setGeometry(QRect(641, 170, 151, 34));
        label_rec_rec_value->setAutoFillBackground(false);
        label_rec_lec_value = new QLabel(centralwidget);
        label_rec_lec_value->setObjectName(QString::fromUtf8("label_rec_lec_value"));
        label_rec_lec_value->setGeometry(QRect(350, 169, 151, 34));
        label_rec_lec_value->setAutoFillBackground(false);
        label_rec_rar_value = new QLabel(centralwidget);
        label_rec_rar_value->setObjectName(QString::fromUtf8("label_rec_rar_value"));
        label_rec_rar_value->setGeometry(QRect(1220, 170, 51, 34));
        label_rec_rar_value->setAutoFillBackground(false);
        label_rec_lar_value = new QLabel(centralwidget);
        label_rec_lar_value->setObjectName(QString::fromUtf8("label_rec_lar_value"));
        label_rec_lar_value->setGeometry(QRect(970, 170, 51, 34));
        label_rec_lar_value->setAutoFillBackground(false);
        label_rec_ampere_value = new QLabel(centralwidget);
        label_rec_ampere_value->setObjectName(QString::fromUtf8("label_rec_ampere_value"));
        label_rec_ampere_value->setGeometry(QRect(38, 170, 91, 34));
        label_rec_ampere_value->setAutoFillBackground(false);
        label_rec_volt_value = new QLabel(centralwidget);
        label_rec_volt_value->setObjectName(QString::fromUtf8("label_rec_volt_value"));
        label_rec_volt_value->setGeometry(QRect(170, 170, 91, 34));
        label_rec_volt_value->setAutoFillBackground(false);
        label_rec_gpio6_value = new QLabel(centralwidget);
        label_rec_gpio6_value->setObjectName(QString::fromUtf8("label_rec_gpio6_value"));
        label_rec_gpio6_value->setGeometry(QRect(300, 288, 21, 34));
        label_rec_gpio1_value = new QLabel(centralwidget);
        label_rec_gpio1_value->setObjectName(QString::fromUtf8("label_rec_gpio1_value"));
        label_rec_gpio1_value->setGeometry(QRect(900, 287, 21, 34));
        label_rec_gpio8_value = new QLabel(centralwidget);
        label_rec_gpio8_value->setObjectName(QString::fromUtf8("label_rec_gpio8_value"));
        label_rec_gpio8_value->setGeometry(QRect(60, 288, 21, 34));
        label_rec_estop_value = new QLabel(centralwidget);
        label_rec_estop_value->setObjectName(QString::fromUtf8("label_rec_estop_value"));
        label_rec_estop_value->setGeometry(QRect(1020, 286, 21, 34));
        label_rec_gpio4_value = new QLabel(centralwidget);
        label_rec_gpio4_value->setObjectName(QString::fromUtf8("label_rec_gpio4_value"));
        label_rec_gpio4_value->setGeometry(QRect(540, 288, 21, 34));
        label_rec_gpio7_value = new QLabel(centralwidget);
        label_rec_gpio7_value->setObjectName(QString::fromUtf8("label_rec_gpio7_value"));
        label_rec_gpio7_value->setGeometry(QRect(180, 288, 21, 34));
        label_rec_gpio2_value = new QLabel(centralwidget);
        label_rec_gpio2_value->setObjectName(QString::fromUtf8("label_rec_gpio2_value"));
        label_rec_gpio2_value->setGeometry(QRect(780, 288, 21, 34));
        label_rec_gpio5_value = new QLabel(centralwidget);
        label_rec_gpio5_value->setObjectName(QString::fromUtf8("label_rec_gpio5_value"));
        label_rec_gpio5_value->setGeometry(QRect(420, 288, 16, 34));
        label_rec_gpio3_value = new QLabel(centralwidget);
        label_rec_gpio3_value->setObjectName(QString::fromUtf8("label_rec_gpio3_value"));
        label_rec_gpio3_value->setGeometry(QRect(660, 288, 21, 34));
        label_rec_cliff_value = new QLabel(centralwidget);
        label_rec_cliff_value->setObjectName(QString::fromUtf8("label_rec_cliff_value"));
        label_rec_cliff_value->setGeometry(QRect(160, 392, 71, 34));
        label_rec_bump_value = new QLabel(centralwidget);
        label_rec_bump_value->setObjectName(QString::fromUtf8("label_rec_bump_value"));
        label_rec_bump_value->setGeometry(QRect(310, 392, 71, 34));
        label_rec_ir_value = new QLabel(centralwidget);
        label_rec_ir_value->setObjectName(QString::fromUtf8("label_rec_ir_value"));
        label_rec_ir_value->setGeometry(QRect(30, 392, 71, 34));
        label_rec_chk_value = new QLabel(centralwidget);
        label_rec_chk_value->setObjectName(QString::fromUtf8("label_rec_chk_value"));
        label_rec_chk_value->setGeometry(QRect(40, 508, 129, 30));
        label_rec_yaw_heading_value = new QLabel(centralwidget);
        label_rec_yaw_heading_value->setObjectName(QString::fromUtf8("label_rec_yaw_heading_value"));
        label_rec_yaw_heading_value->setGeometry(QRect(220, 506, 131, 34));
        label_rec_yaw_vel_value = new QLabel(centralwidget);
        label_rec_yaw_vel_value->setObjectName(QString::fromUtf8("label_rec_yaw_vel_value"));
        label_rec_yaw_vel_value->setGeometry(QRect(426, 506, 131, 34));
        label_tran_chk_value = new QLabel(centralwidget);
        label_tran_chk_value->setObjectName(QString::fromUtf8("label_tran_chk_value"));
        label_tran_chk_value->setGeometry(QRect(1400, 863, 129, 34));
        textEdit = new QTextEdit(centralwidget);
        textEdit->setObjectName(QString::fromUtf8("textEdit"));
        textEdit->setGeometry(QRect(990, 30, 231, 51));
        comboBox_transmit_estop = new QComboBox(centralwidget);
        comboBox_transmit_estop->addItem(QString());
        comboBox_transmit_estop->addItem(QString());
        comboBox_transmit_estop->setObjectName(QString::fromUtf8("comboBox_transmit_estop"));
        comboBox_transmit_estop->setGeometry(QRect(163, 860, 81, 51));
        comboBox_transmit_estop->setEditable(true);
        comboBox_transmit_gpio1 = new QComboBox(centralwidget);
        comboBox_transmit_gpio1->addItem(QString());
        comboBox_transmit_gpio1->addItem(QString());
        comboBox_transmit_gpio1->setObjectName(QString::fromUtf8("comboBox_transmit_gpio1"));
        comboBox_transmit_gpio1->setGeometry(QRect(301, 860, 81, 51));
        comboBox_transmit_gpio1->setEditable(true);
        comboBox_transmit_gpio2 = new QComboBox(centralwidget);
        comboBox_transmit_gpio2->addItem(QString());
        comboBox_transmit_gpio2->addItem(QString());
        comboBox_transmit_gpio2->setObjectName(QString::fromUtf8("comboBox_transmit_gpio2"));
        comboBox_transmit_gpio2->setGeometry(QRect(440, 860, 81, 51));
        comboBox_transmit_gpio2->setEditable(true);
        comboBox_transmit_gpio3 = new QComboBox(centralwidget);
        comboBox_transmit_gpio3->addItem(QString());
        comboBox_transmit_gpio3->addItem(QString());
        comboBox_transmit_gpio3->setObjectName(QString::fromUtf8("comboBox_transmit_gpio3"));
        comboBox_transmit_gpio3->setGeometry(QRect(582, 860, 81, 51));
        comboBox_transmit_gpio3->setEditable(true);
        comboBox_transmit_gpio4 = new QComboBox(centralwidget);
        comboBox_transmit_gpio4->addItem(QString());
        comboBox_transmit_gpio4->addItem(QString());
        comboBox_transmit_gpio4->setObjectName(QString::fromUtf8("comboBox_transmit_gpio4"));
        comboBox_transmit_gpio4->setGeometry(QRect(721, 860, 81, 51));
        comboBox_transmit_gpio4->setEditable(true);
        comboBox_transmit_gpio5 = new QComboBox(centralwidget);
        comboBox_transmit_gpio5->addItem(QString());
        comboBox_transmit_gpio5->addItem(QString());
        comboBox_transmit_gpio5->setObjectName(QString::fromUtf8("comboBox_transmit_gpio5"));
        comboBox_transmit_gpio5->setGeometry(QRect(863, 860, 81, 51));
        comboBox_transmit_gpio5->setEditable(true);
        comboBox_transmit_gpio6 = new QComboBox(centralwidget);
        comboBox_transmit_gpio6->addItem(QString());
        comboBox_transmit_gpio6->addItem(QString());
        comboBox_transmit_gpio6->setObjectName(QString::fromUtf8("comboBox_transmit_gpio6"));
        comboBox_transmit_gpio6->setGeometry(QRect(1003, 860, 81, 51));
        comboBox_transmit_gpio6->setEditable(true);
        comboBox_transmit_gpio7 = new QComboBox(centralwidget);
        comboBox_transmit_gpio7->addItem(QString());
        comboBox_transmit_gpio7->addItem(QString());
        comboBox_transmit_gpio7->setObjectName(QString::fromUtf8("comboBox_transmit_gpio7"));
        comboBox_transmit_gpio7->setGeometry(QRect(1143, 860, 81, 51));
        comboBox_transmit_gpio7->setEditable(true);
        comboBox_transmit_gpio8 = new QComboBox(centralwidget);
        comboBox_transmit_gpio8->addItem(QString());
        comboBox_transmit_gpio8->addItem(QString());
        comboBox_transmit_gpio8->setObjectName(QString::fromUtf8("comboBox_transmit_gpio8"));
        comboBox_transmit_gpio8->setGeometry(QRect(1277, 860, 81, 51));
        comboBox_transmit_gpio8->setEditable(true);
        comboBox_transmit_rdr = new QComboBox(centralwidget);
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->addItem(QString());
        comboBox_transmit_rdr->setObjectName(QString::fromUtf8("comboBox_transmit_rdr"));
        comboBox_transmit_rdr->setGeometry(QRect(1100, 740, 111, 51));
        comboBox_transmit_rdr->setEditable(true);
        comboBox_transmit_ldr = new QComboBox(centralwidget);
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->addItem(QString());
        comboBox_transmit_ldr->setObjectName(QString::fromUtf8("comboBox_transmit_ldr"));
        comboBox_transmit_ldr->setGeometry(QRect(1360, 742, 111, 51));
        comboBox_transmit_ldr->setEditable(true);
        label_debug = new QLabel(centralwidget);
        label_debug->setObjectName(QString::fromUtf8("label_debug"));
        label_debug->setGeometry(QRect(160, 950, 1191, 34));
        label_checksum = new QLabel(centralwidget);
        label_checksum->setObjectName(QString::fromUtf8("label_checksum"));
        label_checksum->setGeometry(QRect(40, 560, 1321, 34));
        MainWindow->setCentralWidget(centralwidget);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "Mobile Robot Protocol Tester v1.0", nullptr));
        label_rec_rar->setText(QCoreApplication::translate("MainWindow", "right acutal rpm", nullptr));
        label_rec_lar->setText(QCoreApplication::translate("MainWindow", "left actual rpm", nullptr));
        label_rec_rec->setText(QCoreApplication::translate("MainWindow", "right encoder count ", nullptr));
        label_rec_volt->setText(QCoreApplication::translate("MainWindow", "volt", nullptr));
        label_rec_ampere->setText(QCoreApplication::translate("MainWindow", "apmere", nullptr));
        label_rec_estop->setText(QCoreApplication::translate("MainWindow", "estop", nullptr));
        label_rec_bump->setText(QCoreApplication::translate("MainWindow", "bump", nullptr));
        label_rec_cliff->setText(QCoreApplication::translate("MainWindow", "cliff", nullptr));
        label_rec_ir->setText(QCoreApplication::translate("MainWindow", "ir", nullptr));
        label_tran_rdr->setText(QCoreApplication::translate("MainWindow", "right desire rpm ", nullptr));
        label_rec_chk->setText(QCoreApplication::translate("MainWindow", "checksum", nullptr));
        label_receive_data->setText(QCoreApplication::translate("MainWindow", "Receive Data ==>", nullptr));
        label_rec_yaw_vel->setText(QCoreApplication::translate("MainWindow", "yaw velocity", nullptr));
        label_rec_yaw_heading->setText(QCoreApplication::translate("MainWindow", "yaw heading", nullptr));
        label_rec_lec->setText(QCoreApplication::translate("MainWindow", "left encoder count ", nullptr));
        label_rec_gpio1->setText(QCoreApplication::translate("MainWindow", "led1", nullptr));
        label_rec_gpio2->setText(QCoreApplication::translate("MainWindow", "led2", nullptr));
        label_rec_gpio3->setText(QCoreApplication::translate("MainWindow", "led3", nullptr));
        label_rec_gpio4->setText(QCoreApplication::translate("MainWindow", "led4", nullptr));
        label_rec_gpio5->setText(QCoreApplication::translate("MainWindow", "gpio5", nullptr));
        label_rec_gpio6->setText(QCoreApplication::translate("MainWindow", "gpio6", nullptr));
        label_rec_gpio7->setText(QCoreApplication::translate("MainWindow", "gpio7", nullptr));
        label_rec_gpio8->setText(QCoreApplication::translate("MainWindow", "gpio8", nullptr));
        label_transmit_data->setText(QCoreApplication::translate("MainWindow", "<== Transmit Data", nullptr));
        label_tran_ldr->setText(QCoreApplication::translate("MainWindow", "left desire rpm ", nullptr));
        label_tran_led1->setText(QCoreApplication::translate("MainWindow", "led1", nullptr));
        label_tran_led6->setText(QCoreApplication::translate("MainWindow", "gpio6", nullptr));
        label_tran_led8->setText(QCoreApplication::translate("MainWindow", "gpio8", nullptr));
        label_tran_estop->setText(QCoreApplication::translate("MainWindow", "estop", nullptr));
        label_tran_led4->setText(QCoreApplication::translate("MainWindow", "led4", nullptr));
        label_tran_led7->setText(QCoreApplication::translate("MainWindow", "gpio7", nullptr));
        label_tran_led2->setText(QCoreApplication::translate("MainWindow", "led2", nullptr));
        label_tran_led3->setText(QCoreApplication::translate("MainWindow", "led3", nullptr));
        label_tran_led5->setText(QCoreApplication::translate("MainWindow", "gpio5", nullptr));
        label_tran_chk->setText(QCoreApplication::translate("MainWindow", "checksum", nullptr));
        label_receive_hz->setText(QCoreApplication::translate("MainWindow", "Hz : ", nullptr));
        label_receive_hz_value->setText(QCoreApplication::translate("MainWindow", "0 ", nullptr));
        connect_btn->setText(QCoreApplication::translate("MainWindow", "Connect", nullptr));
        label_rec_rec_value->setText(QCoreApplication::translate("MainWindow", "xxxxxx", nullptr));
        label_rec_lec_value->setText(QCoreApplication::translate("MainWindow", "xxxxxx", nullptr));
        label_rec_rar_value->setText(QCoreApplication::translate("MainWindow", "xxx", nullptr));
        label_rec_lar_value->setText(QCoreApplication::translate("MainWindow", "xxx", nullptr));
        label_rec_ampere_value->setText(QCoreApplication::translate("MainWindow", "xxxxxx", nullptr));
        label_rec_volt_value->setText(QCoreApplication::translate("MainWindow", "xxxxxx", nullptr));
        label_rec_gpio6_value->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        label_rec_gpio1_value->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        label_rec_gpio8_value->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        label_rec_estop_value->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        label_rec_gpio4_value->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        label_rec_gpio7_value->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        label_rec_gpio2_value->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        label_rec_gpio5_value->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        label_rec_gpio3_value->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        label_rec_cliff_value->setText(QCoreApplication::translate("MainWindow", "xxxx", nullptr));
        label_rec_bump_value->setText(QCoreApplication::translate("MainWindow", "xxxx", nullptr));
        label_rec_ir_value->setText(QCoreApplication::translate("MainWindow", "xxxx", nullptr));
        label_rec_chk_value->setText(QCoreApplication::translate("MainWindow", "xxxxxxxx", nullptr));
        label_rec_yaw_heading_value->setText(QCoreApplication::translate("MainWindow", "xxxxxxxx", nullptr));
        label_rec_yaw_vel_value->setText(QCoreApplication::translate("MainWindow", "xxxxxxxx", nullptr));
        label_tran_chk_value->setText(QCoreApplication::translate("MainWindow", "xxxxxxxx", nullptr));
        textEdit->setHtml(QCoreApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Ubuntu'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">/dev/ttyACM0</p></body></html>", nullptr));
        comboBox_transmit_estop->setItemText(0, QCoreApplication::translate("MainWindow", "0", nullptr));
        comboBox_transmit_estop->setItemText(1, QCoreApplication::translate("MainWindow", "1", nullptr));

        comboBox_transmit_gpio1->setItemText(0, QCoreApplication::translate("MainWindow", "0", nullptr));
        comboBox_transmit_gpio1->setItemText(1, QCoreApplication::translate("MainWindow", "1", nullptr));

        comboBox_transmit_gpio2->setItemText(0, QCoreApplication::translate("MainWindow", "0", nullptr));
        comboBox_transmit_gpio2->setItemText(1, QCoreApplication::translate("MainWindow", "1", nullptr));

        comboBox_transmit_gpio3->setItemText(0, QCoreApplication::translate("MainWindow", "0", nullptr));
        comboBox_transmit_gpio3->setItemText(1, QCoreApplication::translate("MainWindow", "1", nullptr));

        comboBox_transmit_gpio4->setItemText(0, QCoreApplication::translate("MainWindow", "0", nullptr));
        comboBox_transmit_gpio4->setItemText(1, QCoreApplication::translate("MainWindow", "1", nullptr));

        comboBox_transmit_gpio5->setItemText(0, QCoreApplication::translate("MainWindow", "0", nullptr));
        comboBox_transmit_gpio5->setItemText(1, QCoreApplication::translate("MainWindow", "1", nullptr));

        comboBox_transmit_gpio6->setItemText(0, QCoreApplication::translate("MainWindow", "0", nullptr));
        comboBox_transmit_gpio6->setItemText(1, QCoreApplication::translate("MainWindow", "1", nullptr));

        comboBox_transmit_gpio7->setItemText(0, QCoreApplication::translate("MainWindow", "0", nullptr));
        comboBox_transmit_gpio7->setItemText(1, QCoreApplication::translate("MainWindow", "1", nullptr));

        comboBox_transmit_gpio8->setItemText(0, QCoreApplication::translate("MainWindow", "0", nullptr));
        comboBox_transmit_gpio8->setItemText(1, QCoreApplication::translate("MainWindow", "1", nullptr));

        comboBox_transmit_rdr->setItemText(0, QCoreApplication::translate("MainWindow", "70", nullptr));
        comboBox_transmit_rdr->setItemText(1, QCoreApplication::translate("MainWindow", "69", nullptr));
        comboBox_transmit_rdr->setItemText(2, QCoreApplication::translate("MainWindow", "68", nullptr));
        comboBox_transmit_rdr->setItemText(3, QCoreApplication::translate("MainWindow", "67", nullptr));
        comboBox_transmit_rdr->setItemText(4, QCoreApplication::translate("MainWindow", "66", nullptr));
        comboBox_transmit_rdr->setItemText(5, QCoreApplication::translate("MainWindow", "65", nullptr));
        comboBox_transmit_rdr->setItemText(6, QCoreApplication::translate("MainWindow", "64", nullptr));
        comboBox_transmit_rdr->setItemText(7, QCoreApplication::translate("MainWindow", "63", nullptr));
        comboBox_transmit_rdr->setItemText(8, QCoreApplication::translate("MainWindow", "62", nullptr));
        comboBox_transmit_rdr->setItemText(9, QCoreApplication::translate("MainWindow", "61", nullptr));
        comboBox_transmit_rdr->setItemText(10, QCoreApplication::translate("MainWindow", "60", nullptr));
        comboBox_transmit_rdr->setItemText(11, QCoreApplication::translate("MainWindow", "59", nullptr));
        comboBox_transmit_rdr->setItemText(12, QCoreApplication::translate("MainWindow", "58", nullptr));
        comboBox_transmit_rdr->setItemText(13, QCoreApplication::translate("MainWindow", "57", nullptr));
        comboBox_transmit_rdr->setItemText(14, QCoreApplication::translate("MainWindow", "56", nullptr));
        comboBox_transmit_rdr->setItemText(15, QCoreApplication::translate("MainWindow", "55", nullptr));
        comboBox_transmit_rdr->setItemText(16, QCoreApplication::translate("MainWindow", "54", nullptr));
        comboBox_transmit_rdr->setItemText(17, QCoreApplication::translate("MainWindow", "53", nullptr));
        comboBox_transmit_rdr->setItemText(18, QCoreApplication::translate("MainWindow", "52", nullptr));
        comboBox_transmit_rdr->setItemText(19, QCoreApplication::translate("MainWindow", "51", nullptr));
        comboBox_transmit_rdr->setItemText(20, QCoreApplication::translate("MainWindow", "50", nullptr));
        comboBox_transmit_rdr->setItemText(21, QCoreApplication::translate("MainWindow", "49", nullptr));
        comboBox_transmit_rdr->setItemText(22, QCoreApplication::translate("MainWindow", "48", nullptr));
        comboBox_transmit_rdr->setItemText(23, QCoreApplication::translate("MainWindow", "47", nullptr));
        comboBox_transmit_rdr->setItemText(24, QCoreApplication::translate("MainWindow", "46", nullptr));
        comboBox_transmit_rdr->setItemText(25, QCoreApplication::translate("MainWindow", "45", nullptr));
        comboBox_transmit_rdr->setItemText(26, QCoreApplication::translate("MainWindow", "44", nullptr));
        comboBox_transmit_rdr->setItemText(27, QCoreApplication::translate("MainWindow", "43", nullptr));
        comboBox_transmit_rdr->setItemText(28, QCoreApplication::translate("MainWindow", "42", nullptr));
        comboBox_transmit_rdr->setItemText(29, QCoreApplication::translate("MainWindow", "41", nullptr));
        comboBox_transmit_rdr->setItemText(30, QCoreApplication::translate("MainWindow", "40", nullptr));
        comboBox_transmit_rdr->setItemText(31, QCoreApplication::translate("MainWindow", "39", nullptr));
        comboBox_transmit_rdr->setItemText(32, QCoreApplication::translate("MainWindow", "38", nullptr));
        comboBox_transmit_rdr->setItemText(33, QCoreApplication::translate("MainWindow", "37", nullptr));
        comboBox_transmit_rdr->setItemText(34, QCoreApplication::translate("MainWindow", "36", nullptr));
        comboBox_transmit_rdr->setItemText(35, QCoreApplication::translate("MainWindow", "35", nullptr));
        comboBox_transmit_rdr->setItemText(36, QCoreApplication::translate("MainWindow", "34", nullptr));
        comboBox_transmit_rdr->setItemText(37, QCoreApplication::translate("MainWindow", "33", nullptr));
        comboBox_transmit_rdr->setItemText(38, QCoreApplication::translate("MainWindow", "32", nullptr));
        comboBox_transmit_rdr->setItemText(39, QCoreApplication::translate("MainWindow", "31", nullptr));
        comboBox_transmit_rdr->setItemText(40, QCoreApplication::translate("MainWindow", "30", nullptr));
        comboBox_transmit_rdr->setItemText(41, QCoreApplication::translate("MainWindow", "29", nullptr));
        comboBox_transmit_rdr->setItemText(42, QCoreApplication::translate("MainWindow", "28", nullptr));
        comboBox_transmit_rdr->setItemText(43, QCoreApplication::translate("MainWindow", "27", nullptr));
        comboBox_transmit_rdr->setItemText(44, QCoreApplication::translate("MainWindow", "26", nullptr));
        comboBox_transmit_rdr->setItemText(45, QCoreApplication::translate("MainWindow", "25", nullptr));
        comboBox_transmit_rdr->setItemText(46, QCoreApplication::translate("MainWindow", "24", nullptr));
        comboBox_transmit_rdr->setItemText(47, QCoreApplication::translate("MainWindow", "23", nullptr));
        comboBox_transmit_rdr->setItemText(48, QCoreApplication::translate("MainWindow", "22", nullptr));
        comboBox_transmit_rdr->setItemText(49, QCoreApplication::translate("MainWindow", "21", nullptr));
        comboBox_transmit_rdr->setItemText(50, QCoreApplication::translate("MainWindow", "20", nullptr));
        comboBox_transmit_rdr->setItemText(51, QCoreApplication::translate("MainWindow", "19", nullptr));
        comboBox_transmit_rdr->setItemText(52, QCoreApplication::translate("MainWindow", "18", nullptr));
        comboBox_transmit_rdr->setItemText(53, QCoreApplication::translate("MainWindow", "17", nullptr));
        comboBox_transmit_rdr->setItemText(54, QCoreApplication::translate("MainWindow", "16", nullptr));
        comboBox_transmit_rdr->setItemText(55, QCoreApplication::translate("MainWindow", "15", nullptr));
        comboBox_transmit_rdr->setItemText(56, QCoreApplication::translate("MainWindow", "14", nullptr));
        comboBox_transmit_rdr->setItemText(57, QCoreApplication::translate("MainWindow", "13", nullptr));
        comboBox_transmit_rdr->setItemText(58, QCoreApplication::translate("MainWindow", "12", nullptr));
        comboBox_transmit_rdr->setItemText(59, QCoreApplication::translate("MainWindow", "11", nullptr));
        comboBox_transmit_rdr->setItemText(60, QCoreApplication::translate("MainWindow", "10", nullptr));
        comboBox_transmit_rdr->setItemText(61, QCoreApplication::translate("MainWindow", "9", nullptr));
        comboBox_transmit_rdr->setItemText(62, QCoreApplication::translate("MainWindow", "8", nullptr));
        comboBox_transmit_rdr->setItemText(63, QCoreApplication::translate("MainWindow", "7", nullptr));
        comboBox_transmit_rdr->setItemText(64, QCoreApplication::translate("MainWindow", "6", nullptr));
        comboBox_transmit_rdr->setItemText(65, QCoreApplication::translate("MainWindow", "5", nullptr));
        comboBox_transmit_rdr->setItemText(66, QCoreApplication::translate("MainWindow", "4", nullptr));
        comboBox_transmit_rdr->setItemText(67, QCoreApplication::translate("MainWindow", "3", nullptr));
        comboBox_transmit_rdr->setItemText(68, QCoreApplication::translate("MainWindow", "2", nullptr));
        comboBox_transmit_rdr->setItemText(69, QCoreApplication::translate("MainWindow", "1", nullptr));
        comboBox_transmit_rdr->setItemText(70, QCoreApplication::translate("MainWindow", "0", nullptr));
        comboBox_transmit_rdr->setItemText(71, QCoreApplication::translate("MainWindow", "-1", nullptr));
        comboBox_transmit_rdr->setItemText(72, QCoreApplication::translate("MainWindow", "-2", nullptr));
        comboBox_transmit_rdr->setItemText(73, QCoreApplication::translate("MainWindow", "-3", nullptr));
        comboBox_transmit_rdr->setItemText(74, QCoreApplication::translate("MainWindow", "-4", nullptr));
        comboBox_transmit_rdr->setItemText(75, QCoreApplication::translate("MainWindow", "-5", nullptr));
        comboBox_transmit_rdr->setItemText(76, QCoreApplication::translate("MainWindow", "-6", nullptr));
        comboBox_transmit_rdr->setItemText(77, QCoreApplication::translate("MainWindow", "-7", nullptr));
        comboBox_transmit_rdr->setItemText(78, QCoreApplication::translate("MainWindow", "-8", nullptr));
        comboBox_transmit_rdr->setItemText(79, QCoreApplication::translate("MainWindow", "-9", nullptr));
        comboBox_transmit_rdr->setItemText(80, QCoreApplication::translate("MainWindow", "-10", nullptr));
        comboBox_transmit_rdr->setItemText(81, QCoreApplication::translate("MainWindow", "-11", nullptr));
        comboBox_transmit_rdr->setItemText(82, QCoreApplication::translate("MainWindow", "-12", nullptr));
        comboBox_transmit_rdr->setItemText(83, QCoreApplication::translate("MainWindow", "-13", nullptr));
        comboBox_transmit_rdr->setItemText(84, QCoreApplication::translate("MainWindow", "-14", nullptr));
        comboBox_transmit_rdr->setItemText(85, QCoreApplication::translate("MainWindow", "-15", nullptr));
        comboBox_transmit_rdr->setItemText(86, QCoreApplication::translate("MainWindow", "-16", nullptr));
        comboBox_transmit_rdr->setItemText(87, QCoreApplication::translate("MainWindow", "-17", nullptr));
        comboBox_transmit_rdr->setItemText(88, QCoreApplication::translate("MainWindow", "-18", nullptr));
        comboBox_transmit_rdr->setItemText(89, QCoreApplication::translate("MainWindow", "-19", nullptr));
        comboBox_transmit_rdr->setItemText(90, QCoreApplication::translate("MainWindow", "-20", nullptr));
        comboBox_transmit_rdr->setItemText(91, QCoreApplication::translate("MainWindow", "-21", nullptr));
        comboBox_transmit_rdr->setItemText(92, QCoreApplication::translate("MainWindow", "-22", nullptr));
        comboBox_transmit_rdr->setItemText(93, QCoreApplication::translate("MainWindow", "-23", nullptr));
        comboBox_transmit_rdr->setItemText(94, QCoreApplication::translate("MainWindow", "-24", nullptr));
        comboBox_transmit_rdr->setItemText(95, QCoreApplication::translate("MainWindow", "-25", nullptr));
        comboBox_transmit_rdr->setItemText(96, QCoreApplication::translate("MainWindow", "-26", nullptr));
        comboBox_transmit_rdr->setItemText(97, QCoreApplication::translate("MainWindow", "-27", nullptr));
        comboBox_transmit_rdr->setItemText(98, QCoreApplication::translate("MainWindow", "-28", nullptr));
        comboBox_transmit_rdr->setItemText(99, QCoreApplication::translate("MainWindow", "-29", nullptr));
        comboBox_transmit_rdr->setItemText(100, QCoreApplication::translate("MainWindow", "-30", nullptr));
        comboBox_transmit_rdr->setItemText(101, QCoreApplication::translate("MainWindow", "-31", nullptr));
        comboBox_transmit_rdr->setItemText(102, QCoreApplication::translate("MainWindow", "-32", nullptr));
        comboBox_transmit_rdr->setItemText(103, QCoreApplication::translate("MainWindow", "-33", nullptr));
        comboBox_transmit_rdr->setItemText(104, QCoreApplication::translate("MainWindow", "-34", nullptr));
        comboBox_transmit_rdr->setItemText(105, QCoreApplication::translate("MainWindow", "-35", nullptr));
        comboBox_transmit_rdr->setItemText(106, QCoreApplication::translate("MainWindow", "-36", nullptr));
        comboBox_transmit_rdr->setItemText(107, QCoreApplication::translate("MainWindow", "-37", nullptr));
        comboBox_transmit_rdr->setItemText(108, QCoreApplication::translate("MainWindow", "-38", nullptr));
        comboBox_transmit_rdr->setItemText(109, QCoreApplication::translate("MainWindow", "-39", nullptr));
        comboBox_transmit_rdr->setItemText(110, QCoreApplication::translate("MainWindow", "-40", nullptr));
        comboBox_transmit_rdr->setItemText(111, QCoreApplication::translate("MainWindow", "-41", nullptr));
        comboBox_transmit_rdr->setItemText(112, QCoreApplication::translate("MainWindow", "-42", nullptr));
        comboBox_transmit_rdr->setItemText(113, QCoreApplication::translate("MainWindow", "-43", nullptr));
        comboBox_transmit_rdr->setItemText(114, QCoreApplication::translate("MainWindow", "-44", nullptr));
        comboBox_transmit_rdr->setItemText(115, QCoreApplication::translate("MainWindow", "-45", nullptr));
        comboBox_transmit_rdr->setItemText(116, QCoreApplication::translate("MainWindow", "-46", nullptr));
        comboBox_transmit_rdr->setItemText(117, QCoreApplication::translate("MainWindow", "-47", nullptr));
        comboBox_transmit_rdr->setItemText(118, QCoreApplication::translate("MainWindow", "-48", nullptr));
        comboBox_transmit_rdr->setItemText(119, QCoreApplication::translate("MainWindow", "-49", nullptr));
        comboBox_transmit_rdr->setItemText(120, QCoreApplication::translate("MainWindow", "-50", nullptr));
        comboBox_transmit_rdr->setItemText(121, QCoreApplication::translate("MainWindow", "-51", nullptr));
        comboBox_transmit_rdr->setItemText(122, QCoreApplication::translate("MainWindow", "-52", nullptr));
        comboBox_transmit_rdr->setItemText(123, QCoreApplication::translate("MainWindow", "-53", nullptr));
        comboBox_transmit_rdr->setItemText(124, QCoreApplication::translate("MainWindow", "-54", nullptr));
        comboBox_transmit_rdr->setItemText(125, QCoreApplication::translate("MainWindow", "-55", nullptr));
        comboBox_transmit_rdr->setItemText(126, QCoreApplication::translate("MainWindow", "-56", nullptr));
        comboBox_transmit_rdr->setItemText(127, QCoreApplication::translate("MainWindow", "-57", nullptr));
        comboBox_transmit_rdr->setItemText(128, QCoreApplication::translate("MainWindow", "-58", nullptr));
        comboBox_transmit_rdr->setItemText(129, QCoreApplication::translate("MainWindow", "-59", nullptr));
        comboBox_transmit_rdr->setItemText(130, QCoreApplication::translate("MainWindow", "-60", nullptr));
        comboBox_transmit_rdr->setItemText(131, QCoreApplication::translate("MainWindow", "-61", nullptr));
        comboBox_transmit_rdr->setItemText(132, QCoreApplication::translate("MainWindow", "-62", nullptr));
        comboBox_transmit_rdr->setItemText(133, QCoreApplication::translate("MainWindow", "-63", nullptr));
        comboBox_transmit_rdr->setItemText(134, QCoreApplication::translate("MainWindow", "-64", nullptr));
        comboBox_transmit_rdr->setItemText(135, QCoreApplication::translate("MainWindow", "-65", nullptr));
        comboBox_transmit_rdr->setItemText(136, QCoreApplication::translate("MainWindow", "-66", nullptr));
        comboBox_transmit_rdr->setItemText(137, QCoreApplication::translate("MainWindow", "-67", nullptr));
        comboBox_transmit_rdr->setItemText(138, QCoreApplication::translate("MainWindow", "-68", nullptr));
        comboBox_transmit_rdr->setItemText(139, QCoreApplication::translate("MainWindow", "-69", nullptr));
        comboBox_transmit_rdr->setItemText(140, QCoreApplication::translate("MainWindow", "-70", nullptr));

        comboBox_transmit_ldr->setItemText(0, QCoreApplication::translate("MainWindow", "70", nullptr));
        comboBox_transmit_ldr->setItemText(1, QCoreApplication::translate("MainWindow", "69", nullptr));
        comboBox_transmit_ldr->setItemText(2, QCoreApplication::translate("MainWindow", "68", nullptr));
        comboBox_transmit_ldr->setItemText(3, QCoreApplication::translate("MainWindow", "67", nullptr));
        comboBox_transmit_ldr->setItemText(4, QCoreApplication::translate("MainWindow", "66", nullptr));
        comboBox_transmit_ldr->setItemText(5, QCoreApplication::translate("MainWindow", "65", nullptr));
        comboBox_transmit_ldr->setItemText(6, QCoreApplication::translate("MainWindow", "64", nullptr));
        comboBox_transmit_ldr->setItemText(7, QCoreApplication::translate("MainWindow", "63", nullptr));
        comboBox_transmit_ldr->setItemText(8, QCoreApplication::translate("MainWindow", "62", nullptr));
        comboBox_transmit_ldr->setItemText(9, QCoreApplication::translate("MainWindow", "61", nullptr));
        comboBox_transmit_ldr->setItemText(10, QCoreApplication::translate("MainWindow", "60", nullptr));
        comboBox_transmit_ldr->setItemText(11, QCoreApplication::translate("MainWindow", "59", nullptr));
        comboBox_transmit_ldr->setItemText(12, QCoreApplication::translate("MainWindow", "58", nullptr));
        comboBox_transmit_ldr->setItemText(13, QCoreApplication::translate("MainWindow", "57", nullptr));
        comboBox_transmit_ldr->setItemText(14, QCoreApplication::translate("MainWindow", "56", nullptr));
        comboBox_transmit_ldr->setItemText(15, QCoreApplication::translate("MainWindow", "55", nullptr));
        comboBox_transmit_ldr->setItemText(16, QCoreApplication::translate("MainWindow", "54", nullptr));
        comboBox_transmit_ldr->setItemText(17, QCoreApplication::translate("MainWindow", "53", nullptr));
        comboBox_transmit_ldr->setItemText(18, QCoreApplication::translate("MainWindow", "52", nullptr));
        comboBox_transmit_ldr->setItemText(19, QCoreApplication::translate("MainWindow", "51", nullptr));
        comboBox_transmit_ldr->setItemText(20, QCoreApplication::translate("MainWindow", "50", nullptr));
        comboBox_transmit_ldr->setItemText(21, QCoreApplication::translate("MainWindow", "49", nullptr));
        comboBox_transmit_ldr->setItemText(22, QCoreApplication::translate("MainWindow", "48", nullptr));
        comboBox_transmit_ldr->setItemText(23, QCoreApplication::translate("MainWindow", "47", nullptr));
        comboBox_transmit_ldr->setItemText(24, QCoreApplication::translate("MainWindow", "46", nullptr));
        comboBox_transmit_ldr->setItemText(25, QCoreApplication::translate("MainWindow", "45", nullptr));
        comboBox_transmit_ldr->setItemText(26, QCoreApplication::translate("MainWindow", "44", nullptr));
        comboBox_transmit_ldr->setItemText(27, QCoreApplication::translate("MainWindow", "43", nullptr));
        comboBox_transmit_ldr->setItemText(28, QCoreApplication::translate("MainWindow", "42", nullptr));
        comboBox_transmit_ldr->setItemText(29, QCoreApplication::translate("MainWindow", "41", nullptr));
        comboBox_transmit_ldr->setItemText(30, QCoreApplication::translate("MainWindow", "40", nullptr));
        comboBox_transmit_ldr->setItemText(31, QCoreApplication::translate("MainWindow", "39", nullptr));
        comboBox_transmit_ldr->setItemText(32, QCoreApplication::translate("MainWindow", "38", nullptr));
        comboBox_transmit_ldr->setItemText(33, QCoreApplication::translate("MainWindow", "37", nullptr));
        comboBox_transmit_ldr->setItemText(34, QCoreApplication::translate("MainWindow", "36", nullptr));
        comboBox_transmit_ldr->setItemText(35, QCoreApplication::translate("MainWindow", "35", nullptr));
        comboBox_transmit_ldr->setItemText(36, QCoreApplication::translate("MainWindow", "34", nullptr));
        comboBox_transmit_ldr->setItemText(37, QCoreApplication::translate("MainWindow", "33", nullptr));
        comboBox_transmit_ldr->setItemText(38, QCoreApplication::translate("MainWindow", "32", nullptr));
        comboBox_transmit_ldr->setItemText(39, QCoreApplication::translate("MainWindow", "31", nullptr));
        comboBox_transmit_ldr->setItemText(40, QCoreApplication::translate("MainWindow", "30", nullptr));
        comboBox_transmit_ldr->setItemText(41, QCoreApplication::translate("MainWindow", "29", nullptr));
        comboBox_transmit_ldr->setItemText(42, QCoreApplication::translate("MainWindow", "28", nullptr));
        comboBox_transmit_ldr->setItemText(43, QCoreApplication::translate("MainWindow", "27", nullptr));
        comboBox_transmit_ldr->setItemText(44, QCoreApplication::translate("MainWindow", "26", nullptr));
        comboBox_transmit_ldr->setItemText(45, QCoreApplication::translate("MainWindow", "25", nullptr));
        comboBox_transmit_ldr->setItemText(46, QCoreApplication::translate("MainWindow", "24", nullptr));
        comboBox_transmit_ldr->setItemText(47, QCoreApplication::translate("MainWindow", "23", nullptr));
        comboBox_transmit_ldr->setItemText(48, QCoreApplication::translate("MainWindow", "22", nullptr));
        comboBox_transmit_ldr->setItemText(49, QCoreApplication::translate("MainWindow", "21", nullptr));
        comboBox_transmit_ldr->setItemText(50, QCoreApplication::translate("MainWindow", "20", nullptr));
        comboBox_transmit_ldr->setItemText(51, QCoreApplication::translate("MainWindow", "19", nullptr));
        comboBox_transmit_ldr->setItemText(52, QCoreApplication::translate("MainWindow", "18", nullptr));
        comboBox_transmit_ldr->setItemText(53, QCoreApplication::translate("MainWindow", "17", nullptr));
        comboBox_transmit_ldr->setItemText(54, QCoreApplication::translate("MainWindow", "16", nullptr));
        comboBox_transmit_ldr->setItemText(55, QCoreApplication::translate("MainWindow", "15", nullptr));
        comboBox_transmit_ldr->setItemText(56, QCoreApplication::translate("MainWindow", "14", nullptr));
        comboBox_transmit_ldr->setItemText(57, QCoreApplication::translate("MainWindow", "13", nullptr));
        comboBox_transmit_ldr->setItemText(58, QCoreApplication::translate("MainWindow", "12", nullptr));
        comboBox_transmit_ldr->setItemText(59, QCoreApplication::translate("MainWindow", "11", nullptr));
        comboBox_transmit_ldr->setItemText(60, QCoreApplication::translate("MainWindow", "10", nullptr));
        comboBox_transmit_ldr->setItemText(61, QCoreApplication::translate("MainWindow", "9", nullptr));
        comboBox_transmit_ldr->setItemText(62, QCoreApplication::translate("MainWindow", "8", nullptr));
        comboBox_transmit_ldr->setItemText(63, QCoreApplication::translate("MainWindow", "7", nullptr));
        comboBox_transmit_ldr->setItemText(64, QCoreApplication::translate("MainWindow", "6", nullptr));
        comboBox_transmit_ldr->setItemText(65, QCoreApplication::translate("MainWindow", "5", nullptr));
        comboBox_transmit_ldr->setItemText(66, QCoreApplication::translate("MainWindow", "4", nullptr));
        comboBox_transmit_ldr->setItemText(67, QCoreApplication::translate("MainWindow", "3", nullptr));
        comboBox_transmit_ldr->setItemText(68, QCoreApplication::translate("MainWindow", "2", nullptr));
        comboBox_transmit_ldr->setItemText(69, QCoreApplication::translate("MainWindow", "1", nullptr));
        comboBox_transmit_ldr->setItemText(70, QCoreApplication::translate("MainWindow", "0", nullptr));
        comboBox_transmit_ldr->setItemText(71, QCoreApplication::translate("MainWindow", "-1", nullptr));
        comboBox_transmit_ldr->setItemText(72, QCoreApplication::translate("MainWindow", "-2", nullptr));
        comboBox_transmit_ldr->setItemText(73, QCoreApplication::translate("MainWindow", "-3", nullptr));
        comboBox_transmit_ldr->setItemText(74, QCoreApplication::translate("MainWindow", "-4", nullptr));
        comboBox_transmit_ldr->setItemText(75, QCoreApplication::translate("MainWindow", "-5", nullptr));
        comboBox_transmit_ldr->setItemText(76, QCoreApplication::translate("MainWindow", "-6", nullptr));
        comboBox_transmit_ldr->setItemText(77, QCoreApplication::translate("MainWindow", "-7", nullptr));
        comboBox_transmit_ldr->setItemText(78, QCoreApplication::translate("MainWindow", "-8", nullptr));
        comboBox_transmit_ldr->setItemText(79, QCoreApplication::translate("MainWindow", "-9", nullptr));
        comboBox_transmit_ldr->setItemText(80, QCoreApplication::translate("MainWindow", "-10", nullptr));
        comboBox_transmit_ldr->setItemText(81, QCoreApplication::translate("MainWindow", "-11", nullptr));
        comboBox_transmit_ldr->setItemText(82, QCoreApplication::translate("MainWindow", "-12", nullptr));
        comboBox_transmit_ldr->setItemText(83, QCoreApplication::translate("MainWindow", "-13", nullptr));
        comboBox_transmit_ldr->setItemText(84, QCoreApplication::translate("MainWindow", "-14", nullptr));
        comboBox_transmit_ldr->setItemText(85, QCoreApplication::translate("MainWindow", "-15", nullptr));
        comboBox_transmit_ldr->setItemText(86, QCoreApplication::translate("MainWindow", "-16", nullptr));
        comboBox_transmit_ldr->setItemText(87, QCoreApplication::translate("MainWindow", "-17", nullptr));
        comboBox_transmit_ldr->setItemText(88, QCoreApplication::translate("MainWindow", "-18", nullptr));
        comboBox_transmit_ldr->setItemText(89, QCoreApplication::translate("MainWindow", "-19", nullptr));
        comboBox_transmit_ldr->setItemText(90, QCoreApplication::translate("MainWindow", "-20", nullptr));
        comboBox_transmit_ldr->setItemText(91, QCoreApplication::translate("MainWindow", "-21", nullptr));
        comboBox_transmit_ldr->setItemText(92, QCoreApplication::translate("MainWindow", "-22", nullptr));
        comboBox_transmit_ldr->setItemText(93, QCoreApplication::translate("MainWindow", "-23", nullptr));
        comboBox_transmit_ldr->setItemText(94, QCoreApplication::translate("MainWindow", "-24", nullptr));
        comboBox_transmit_ldr->setItemText(95, QCoreApplication::translate("MainWindow", "-25", nullptr));
        comboBox_transmit_ldr->setItemText(96, QCoreApplication::translate("MainWindow", "-26", nullptr));
        comboBox_transmit_ldr->setItemText(97, QCoreApplication::translate("MainWindow", "-27", nullptr));
        comboBox_transmit_ldr->setItemText(98, QCoreApplication::translate("MainWindow", "-28", nullptr));
        comboBox_transmit_ldr->setItemText(99, QCoreApplication::translate("MainWindow", "-29", nullptr));
        comboBox_transmit_ldr->setItemText(100, QCoreApplication::translate("MainWindow", "-30", nullptr));
        comboBox_transmit_ldr->setItemText(101, QCoreApplication::translate("MainWindow", "-31", nullptr));
        comboBox_transmit_ldr->setItemText(102, QCoreApplication::translate("MainWindow", "-32", nullptr));
        comboBox_transmit_ldr->setItemText(103, QCoreApplication::translate("MainWindow", "-33", nullptr));
        comboBox_transmit_ldr->setItemText(104, QCoreApplication::translate("MainWindow", "-34", nullptr));
        comboBox_transmit_ldr->setItemText(105, QCoreApplication::translate("MainWindow", "-35", nullptr));
        comboBox_transmit_ldr->setItemText(106, QCoreApplication::translate("MainWindow", "-36", nullptr));
        comboBox_transmit_ldr->setItemText(107, QCoreApplication::translate("MainWindow", "-37", nullptr));
        comboBox_transmit_ldr->setItemText(108, QCoreApplication::translate("MainWindow", "-38", nullptr));
        comboBox_transmit_ldr->setItemText(109, QCoreApplication::translate("MainWindow", "-39", nullptr));
        comboBox_transmit_ldr->setItemText(110, QCoreApplication::translate("MainWindow", "-40", nullptr));
        comboBox_transmit_ldr->setItemText(111, QCoreApplication::translate("MainWindow", "-41", nullptr));
        comboBox_transmit_ldr->setItemText(112, QCoreApplication::translate("MainWindow", "-42", nullptr));
        comboBox_transmit_ldr->setItemText(113, QCoreApplication::translate("MainWindow", "-43", nullptr));
        comboBox_transmit_ldr->setItemText(114, QCoreApplication::translate("MainWindow", "-44", nullptr));
        comboBox_transmit_ldr->setItemText(115, QCoreApplication::translate("MainWindow", "-45", nullptr));
        comboBox_transmit_ldr->setItemText(116, QCoreApplication::translate("MainWindow", "-46", nullptr));
        comboBox_transmit_ldr->setItemText(117, QCoreApplication::translate("MainWindow", "-47", nullptr));
        comboBox_transmit_ldr->setItemText(118, QCoreApplication::translate("MainWindow", "-48", nullptr));
        comboBox_transmit_ldr->setItemText(119, QCoreApplication::translate("MainWindow", "-49", nullptr));
        comboBox_transmit_ldr->setItemText(120, QCoreApplication::translate("MainWindow", "-50", nullptr));
        comboBox_transmit_ldr->setItemText(121, QCoreApplication::translate("MainWindow", "-51", nullptr));
        comboBox_transmit_ldr->setItemText(122, QCoreApplication::translate("MainWindow", "-52", nullptr));
        comboBox_transmit_ldr->setItemText(123, QCoreApplication::translate("MainWindow", "-53", nullptr));
        comboBox_transmit_ldr->setItemText(124, QCoreApplication::translate("MainWindow", "-54", nullptr));
        comboBox_transmit_ldr->setItemText(125, QCoreApplication::translate("MainWindow", "-55", nullptr));
        comboBox_transmit_ldr->setItemText(126, QCoreApplication::translate("MainWindow", "-56", nullptr));
        comboBox_transmit_ldr->setItemText(127, QCoreApplication::translate("MainWindow", "-57", nullptr));
        comboBox_transmit_ldr->setItemText(128, QCoreApplication::translate("MainWindow", "-58", nullptr));
        comboBox_transmit_ldr->setItemText(129, QCoreApplication::translate("MainWindow", "-59", nullptr));
        comboBox_transmit_ldr->setItemText(130, QCoreApplication::translate("MainWindow", "-60", nullptr));
        comboBox_transmit_ldr->setItemText(131, QCoreApplication::translate("MainWindow", "-61", nullptr));
        comboBox_transmit_ldr->setItemText(132, QCoreApplication::translate("MainWindow", "-62", nullptr));
        comboBox_transmit_ldr->setItemText(133, QCoreApplication::translate("MainWindow", "-63", nullptr));
        comboBox_transmit_ldr->setItemText(134, QCoreApplication::translate("MainWindow", "-64", nullptr));
        comboBox_transmit_ldr->setItemText(135, QCoreApplication::translate("MainWindow", "-65", nullptr));
        comboBox_transmit_ldr->setItemText(136, QCoreApplication::translate("MainWindow", "-66", nullptr));
        comboBox_transmit_ldr->setItemText(137, QCoreApplication::translate("MainWindow", "-67", nullptr));
        comboBox_transmit_ldr->setItemText(138, QCoreApplication::translate("MainWindow", "-68", nullptr));
        comboBox_transmit_ldr->setItemText(139, QCoreApplication::translate("MainWindow", "-69", nullptr));
        comboBox_transmit_ldr->setItemText(140, QCoreApplication::translate("MainWindow", "-70", nullptr));

        label_debug->setText(QString());
        label_checksum->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
